### ISSUE TITLE
[Bug]: Changing the RPC app name doesn't work

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#11]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

Changing the `Connectivity -> Discord Rich Presence` setting to `AppleMusic` doesn't actually update the rich presence app name. It always appears as "Playing Cider 2".

### Steps to Reproduce

1. Open settings menu
2. Open Connectivity
3. Change Discord Rich Presence from Cider-2 to AppleMusic

**Comment by Swiftzerr** [comment]
Fixed in #84
