### ISSUE TITLE
[Bug]: Shuffle button not working on playlists with over 100 songs

### ISSUE THREAD

**Issue by oEnchanted** [ciderapp/Fujisan-BugTracker#2]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10/11/All

### Describe the Bug

When clicking the shuffle button on a large playlist, Cider will only play the first 100 or so songs in the playlist and ignore everything else. The only workaround has been clicking on a song, then enabling shuffle, then skipping that song.

### Steps to Reproduce

Create a playlist with 150-300+ songs and try to shuffle, it'll happen.

**Comment by booploops** [comment]
resolved in latest SPA
