### ISSUE TITLE
[Bug]: Menu bar dissapears from Cider - Permanent 

### ISSUE THREAD

**Issue by JimDude7404** [ciderapp/Fujisan-BugTracker#20]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 

### Describe the Bug

The menu at the top ran away!
![image](https://user-images.githubusercontent.com/67085206/223315129-2aca0741-1c3e-4bc1-936f-e1b270bb010b.png)

### Steps to Reproduce

1. Went to library and this happend

**Comment by JimDude7404** [comment]
Whatever the hell happend, it permanent

**Comment by booploops** [comment]
resolved in latest SPA
