### ISSUE TITLE
[Bug]: "Start Radio" does nothing on stations

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#23]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

This one's extremely nitpick-y, but since that's the plan I'm reporting it.

## Current behavior

The "Start Radio" option shows when right clicking/clicking the overflow menu on a station item. Selecting the option does nothing.

![Cider_IR2msz09ER](https://user-images.githubusercontent.com/56169608/223316781-4183ad07-b73f-44be-b6c1-c811de56c2ff.png)

![Cider_Hv9zlYoLmG](https://user-images.githubusercontent.com/56169608/223316647-4ee0dfb8-48f8-47ff-9898-0204a4ba7b17.png)

## Expected behavior

Two options:
1. Start the station normally
2. Hide this option for station items

### Steps to Reproduce

1. Right click on a station item (either in the Made For You/Friends Listening section or in your recently played section)
2. Click "Start Radio"

**Comment by Swiftzerr** [comment]
Fixed in latest commit, thanks for reporting!
