### ISSUE TITLE
[Bug]: Losing focus causes song.link to fail to attach to clipboard when completed

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#24]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

This might just be how Windows app security handles clipboard contents.

## Current behavior

When copying a song.link link and immediately focusing to another tab, a "Failed to copy" toast appears and the link isn't copied. The same behavior occurs even after the song.link request has already been made for that song and you copy the link again.

## Expected behavior

The song.link link should be copied in the background.

### Steps to Reproduce

1. Right click a song
2. Mouse over "Share..."
3. Click "Copy with song.link"
4. Tab out of the window before it copies to your clipboard
5. Preview the Cider window by hovering over the taskbar icon until you see the red toast appear

**Comment by d3rpp** [comment]
My best guess is this is webview being cringe and not letting us access the clipboard to put the link in there.

Part of me wants to say this is intended behaviour because iirc there's not much we can do about it.

If the webview instance allowed access to the clipboard when not in focus, it would allow someone to just spam the clipboard in the background :/

**Comment by d3rpp** [comment]
Nonetheless, will look into it

**Comment by TreehouseFalcon** [comment]
This was fixed with last night's Sabiiro prerelease build.
