### ISSUE TITLE
[Bug]: Cider Audio Lab disappears

### ISSUE THREAD

**Issue by PixlM** [ciderapp/Fujisan-BugTracker#25]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10, Version 10.0.19045 Build 19045

### Describe the Bug

There is no icon to toggle Cider Audio Lab. It is completely gone from the main screen.

### Steps to Reproduce

Version WLDjUfy
Settings > audio > Cider Audio for Apple Music > ON
Restart.
Icon Missing from top right

### Anything else?

![image](https://user-images.githubusercontent.com/50971434/223324278-5051130f-ef7e-4538-9479-f74404546ef4.png)
![image](https://user-images.githubusercontent.com/50971434/223324319-f3963d06-d8e7-4042-bada-b458725767db.png)

**Comment by booploops** [comment]
resolved in latest SPA
