### ISSUE TITLE
[Bug/Visual]: Now Playing bar does not show song's album adjacent to artist

### ISSUE THREAD

**Issue by Enstrayed** [ciderapp/Fujisan-BugTracker#3]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 Pro 22H2 22624.1391

### Describe the Bug

The now playing bar does not have a songs album adjacent to the songs artist. 
I believe (based on nothing) that this used to be there, and I feel like it should come back or be a toggle.

### Steps to Reproduce

1. Play a song
2. **observe** the now playing bar

### Anything else?

nop

**Comment by Monochromish** [comment]
Added back.
