### ISSUE TITLE
[Bug]: Listen Now — Missing category `reason` subtitles (edge case/nitpick)

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Fujisan-BugTracker#34]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

The `reason` field in the Listen Now categories are kinda new and only appears in a few of them. However, Apple Music on iOS already supports them and the <abbr title="Apple Music">AM</abbr> API responds the following:

![image](https://user-images.githubusercontent.com/32032824/223416314-6e4fb96a-4c62-4e02-9178-c16f8d27f452.png)
*Example API Response*

### Steps to Reproduce

1. Open Listen Now
2. If you get lucky, you will find a category that support it
3. Their subtitle are not displayed

### Anything else?

![image](https://user-images.githubusercontent.com/32032824/223414181-7df79b7f-4dd3-47a0-8844-9f841b67d594.png)
*Apple Music iOS app*

**Comment by Swiftzerr** [comment]
Yet to find a listen now section with this reason but I will add it for display nonetheless

**Comment by Swiftzerr** [comment]
Added in latest commit, thanks for reporting!
