### ISSUE TITLE
[Bug]: Genre/Curator attributions not linking (nitpick)

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Fujisan-BugTracker#38]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

I would love to see Cider be able to tap into a playlist's curator information and properly link them within the attributions (small text below the title)

![PowerToys_o2g3CEqZjv](https://user-images.githubusercontent.com/32032824/223440382-762d7d7a-c181-49a5-89b9-ef011cc50d88.gif)

### Steps to Reproduce

Try clicking on a recommended playlist's curator attribution.

**Comment by Swiftzerr** [comment]
Looking into this

**Comment by Swiftzerr** [comment]
Issue fixed in latest commit, thanks for reporting

**Comment by SoNothingMC** [comment]
So… this isn't working again. pls fix

**Comment by Swiftzerr** [comment]
Fixed again
