### ISSUE TITLE
[Visual Suggestion]: Dislike button is filled in by default, making it look like you have disliked a song.

### ISSUE THREAD

**Issue by oEnchanted** [ciderapp/Fujisan-BugTracker#4]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10/11/All

### Describe the Bug

When right-clicking on a song or playlist, the thumbs-down button is filled in making it appear that you have disliked a song when you haven't. This seems like more of a design oversight than anything.

### Steps to Reproduce

Right click on any song/playlist
![image](https://user-images.githubusercontent.com/49955460/223299567-f28235e8-758b-4074-bf29-231f2341c64b.png)

**Comment by Enstrayed** [comment]
Can replicate (Windows 11 Pro 22H2 22624.1391)
This should be prioritized

**Comment by d3rpp** [comment]
I agree with this, it looks rarted, I'll get on it

**Comment by booploops** [comment]
resolved in latest SPA
