### ISSUE TITLE
[Bug]: Width/Height in URLs are swapped in Properties modal

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Fujisan-BugTracker#40]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

The `w` and the `h` value in links that open when you click an image in the Properties modal is swapped.

```
https://is2-ssl.mzstatic.com/image/thumb/Features122/v4/0a/e5/ae/0ae5ae0b-0cff-b79a-c3a0-de499d596df3/ac87d78f-3f14-4ba5-b471-0621ac629054.png/1080x4320bb.jpg
                                                                                                                                               ↳ here!
```
The correct URL should end in `4320x1080bb.jpg`.

### Steps to Reproduce

1. Go to any album with a Editorial Image
2. Click Properties → Artwork
3. Click on the hero images
4. See swapped w/h values in the URL and image

**Comment by Swiftzerr** [comment]
Fixed in latest commit
