### ISSUE TITLE
[Bug]: Removing albums and refreshing list doesn't fully sync changes

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#42]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/223507135-e2870e46-edaa-4bbc-8d8e-5078d6fe210e.png)
Album menu in Library will still show remnants of songs removed sometimes even after refreshing the list.

### Steps to Reproduce

Go to albums menu, remove some albums, refresh albums page with the refresh button.

**Comment by coredev-uk** [comment]
The Apple Music API does take a minute or two for it to update. This should be resolved whenever the new clientdb gets merged, but until then you will just need to give it a couple of minutes then refresh and/or restart the app.
