### ISSUE TITLE
[Bug]: Window does not remember placement when app restarted

### ISSUE THREAD

**Issue by joshrsmith** [ciderapp/Fujisan-BugTracker#51]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10

### Describe the Bug

In Cider 1.x, the app would remember where it was when you last closed it. When you open it the next time, it would open in the same place. This is especially good for people with multiple monitor setups.

### Steps to Reproduce

* Open the app
* Move the app window to location on your screen where you like it
* Close the app
* Open the app again
* App opens in the same position as first time, not where it was closed.

**Comment by coredev-uk** [comment]
Merging into #51
