### ISSUE TITLE
[Bug]: `multi-room` type pages open in iTunes

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Fujisan-BugTracker#52]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

Cider doesn't support `mutli-room`s (also known as Collections), which appears frequently as the headline item in the Browse page (and permanently featured in genres such as Apple Music Anime).

### Steps to Reproduce

1. Open Browse
2. Click on the International Women's Day banner

_OR…_

1. Open Browse and scroll to the bottom
2. Click Browse by Category
4. Click Anime
5. Scroll the carousel all the way to the right
6. Click on the "SPY×FAMILY" soundtrack collection or the "Project Sekai: Colorful Stage!" soundtrack collection (content will be different depending on your storefront)

Result: An Microsoft Edge popup appears, which then attempts to open iTunes

### Anything else?

This feature was previously implemented within Cider 1.

**Comment by Swiftzerr** [comment]
Fixed in latest commit, thanks for reporting!
