### ISSUE TITLE
[Bug]: (TINY NITPICK) Apple Music slider is disabled in Account settings

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#58]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

Since crypto said to "get really nitpicky", here it is.

## Current behavior

The slider for Apple Music is disabled in account settings.

## Expected behavior

The slider should be enabled, as Apple Music is the only streaming service supported by Cider currently.

### Steps to Reproduce

1. Open settings
2. Go to Accounts
3. Locate Apple Music

**Comment by Monochromish** [comment]
yup made the changes lmao
