### ISSUE TITLE
[Bug]: Artist buttons on Recently Added page no longer work

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#61]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/223875638-f92115f3-0d06-49ff-8e5c-67ed86705e7e.png)
Left click to link to the artist page of a playlist or song on the Recently Added page no longer works as expected.

### Steps to Reproduce

Go to recently added page, then try to left click any artist name under the name of the song/playlist. Will increase CPU usage of Cider but not actually link to anything.

**Comment by Swiftzerr** [comment]
I couldn't replicate this issue.  Could you share a screenshot of your console? This can be accessed using CTRL/CMD + SHIFT + I

**Comment by NotChanceBanana** [comment]
Console has been inaccessible for me on this build, ctrl shift I doesnt do anything for me. Starting to think my install might just be incredibly scuffed lol

**Comment by Swiftzerr** [comment]
Im going to close this because it seems like a weird issue on your end, try fully removing your %appdata%/Cider-2 folder.

**Comment by NotChanceBanana** [comment]
Fixed in latest build.
