### ISSUE TITLE
[Bug]: Custom/user created playlists from within Cider only show 3 songs total

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#62]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/223876509-24c87687-6b00-490f-a717-f6d7ca62a45e.png)
![image](https://user-images.githubusercontent.com/123398780/223876550-bfaaf6bd-7614-45a0-ab8b-d70c893b5971.png)
Playlists I had added/created via Cider in the past now only show 3 songs total, and the same 3 songs. App is logged in via Apple music but not Cider connect.

### Steps to Reproduce

Have cider open, make sure you are signed in via apple music but not Cider connect, or log out of connect but stay signed into apple music, it should show custom playlists as still existing but with less songs available for whatever reason. (Might be tied to Cider Connect issues?)

**Comment by Monochromish** [comment]
could you please verify whether the playlist shows more than three songs on the native Apple Music app/iTunes? If it does, it's probably related to MusicKit and its authorization with Apple Music services. In that situation, you should try logging in again.

**Comment by NotChanceBanana** [comment]
Signing in and out does not fix the problem on latest build - bug has persisted between previous and latest build.

**Comment by NotChanceBanana** [comment]
Found and fixed problem, it was not syncing correctly but signing in and out fixed it.
