### ISSUE TITLE
[Bug]: Artist page button no longer works in more places

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#63]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/223877870-76866578-5fc1-4a54-969b-a730368b63d8.png)
None of the artist buttons on the Songs page will link to the artists.

### Steps to Reproduce

Open songs page in C2, attempt to interact with any of the artist buttons that would link to the artist pages, will not work for any of them.

**Comment by Swiftzerr** [comment]
Closing for same reason as #62

**Comment by NotChanceBanana** [comment]
Fixed in latest build.
