### ISSUE TITLE
[Bug/Visual]: The translucent sidebar in the settings menu is too translucent. 

### ISSUE THREAD

**Issue by Enstrayed** [ciderapp/Fujisan-BugTracker#7]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 Pro 22H2 22624.1391

### Describe the Bug

When opening the settings menu, the sidebar is too clear, easily allowing you to see playlist text behind it. This is quite visually messy. 

See attached image 

![cider 2 settings sidebar](https://on.enstrayed.com/images/20230306cider2settingssidebar.jpg)

### Steps to Reproduce

1. open the settings menu
2. **observe** the sidebar

**Comment by booploops** [comment]
resolved in "visual quirks" commit
