### ISSUE TITLE
[UI Suggestion]: Use Adaptive Color for UI accent color (Currently red)

### ISSUE THREAD

**Issue by solibule** [ciderapp/Fujisan-BugTracker#72]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

The red in Immersive currently detracts from songs which have art that clashes with it.
![image](https://user-images.githubusercontent.com/75220305/223974131-afbd017e-9621-4b6a-8c8e-560c97719dcb.png)
Instead, a more saturated and darker version of the Adaptive Window Color, or a blend of the stock background color and the Adaptive Color, would be more suitable as to not detract from the Immersive experience.

### Steps to Reproduce

N/A

**Comment by Swiftzerr** [comment]
added in latest commit
