### ISSUE TITLE
[Bug]: Duplicate songs in Songs library show as blank entries

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#73]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/224102850-9a958a88-ee21-4886-a50b-3316235a2fde.png)
![image](https://user-images.githubusercontent.com/123398780/224102887-3eed62d5-579f-4f68-8fde-2f8d20481f20.png)
Both of these should be added to my library and show up in Songs, but they do not.

### Steps to Reproduce

Find a song that has a duplicated entry in Apple Music, add both to library, go to Songs tab, one will be completely blank.

**Comment by coredev-uk** [comment]
Are you using the latest build?

**Comment by NotChanceBanana** [comment]
Yes, I am on latest build, unlike the previous build I am able to fix it by reloading/refreshing the songs page.
