### ISSUE TITLE
[UI Nitpick]: Artist button scale for currently playing song seems incorrect

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#74]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/224104470-08cf5074-761c-47cd-8037-b4dec87deb1e.png)
When playing a song, if you scroll over to the name of the artist under the song name, the button scale completely ignores the text currently there and will do a max size/length button regardless of the artist name's length. 

### Steps to Reproduce

I think this could be improved to exactly or roughly match the text length of the artist name, it would feel less clunky and lead to less accidental presses (whenever clicking on it to link to artist page gets fixed).
![image](https://user-images.githubusercontent.com/123398780/224105244-425abd3a-5ac0-48c2-bf36-1e847b582e8f.png)

**Comment by Swiftzerr** [comment]
Fixed in latest commit
