### ISSUE TITLE
[Bug]: Infinitely loading artist link in context menu

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#76]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/224241471-1086c945-8c1a-46a8-89f5-6b99f6a065d6.png)
When you Right click the artist name of the currently playing song and click on "go to artist" in the following context menu, it will infinitely load with the wheel of death.

### Steps to Reproduce

Play a song, right click artist name in the currently playing section, then click on "go to artist" in the following context menu.

**Comment by Swiftzerr** [comment]
Fixed in latest commit

**Comment by Swiftzerr** [comment]
Fixed in latest commit

**Comment by NotChanceBanana** [comment]
It's not fixed for me in latest build lol

**Comment by Swiftzerr** [comment]
@NotChanceBanana is it still not fixed?

**Comment by NotChanceBanana** [comment]
This has been fixed in latest Sabiiro builds, thank you!
