### ISSUE TITLE
[Bug]: Unnecessary scrollbar appearing in portrait Immersive mode

### ISSUE THREAD

**Issue by numanumaa** [ciderapp/Fujisan-BugTracker#78]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

A scrollbar appears in Immersive mode when Cider is scaled to a portrait view; it doesn't have any apparent useful functionality. Ideally it should be removed.

![scrollbar](https://user-images.githubusercontent.com/79871965/224458386-a15fbe97-1d3b-415f-b208-4717775c43a4.gif)

### Steps to Reproduce

1. Play a song
2. Open Immersive mode
3. Scale Cider to a portrait view

**Comment by Swiftzerr** [comment]
Fixed in latest commit
