### ISSUE TITLE
[Bug]: Artist link doesn't work in current song section

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#80]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

## Current behavior

Clicking the artist name in the current song section doesn't redirect me to the artist page.
![Cider_SydUe9I48b](https://user-images.githubusercontent.com/56169608/224506891-144598d6-6f60-4826-9cf6-eddb1117221f.png)

## Expected behavior

Since this link is clickable, it should send me to the artist's page.

### Steps to Reproduce

1. Play your personal station
2. Click the artist's name

**Comment by jacksonwelsh** [comment]
Also does not work in the Mojave layout.

**Comment by Monochromish** [comment]
not able to replicate the issue. the redirect appears to be working fine for me on both the maverick and mojave layouts. can you please provide a screenshot of the logs when you try to click on the link?

@TreehouseFalcon @jacksonwelsh

**Comment by coredev-uk** [comment]
Is this an iCloud uploaded song?

**Comment by TreehouseFalcon** [comment]
This was not an iTunes song, but it seems to be fixed in the latest build.
