### ISSUE TITLE
[UX]: A toast should appear after a song is added to a playlist

### ISSUE THREAD

**Issue by TreehouseFalcon** [ciderapp/Fujisan-BugTracker#81]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

## Current behavior 

When adding a song to a playlist it's unclear when/if the song is actually added. The popover menu just disappears after playlist selection. For things such as liking/disliking songs or removing them from the library, you get visual feedback via the icon changing.

## Expected behavior

When the network request to add the song to a playlist settles, a toast should appear (similar to the song.link copy toast) giving you visual confirmation whether the song was added to the playlist or not.

### Steps to Reproduce

1. Open overflow menu on a song
2. Add song to a playlist

**Comment by Monochromish** [comment]
Added.
