### ISSUE TITLE
[Bug]: Playlist sorting

### ISSUE THREAD

**Issue by BENZORICH** [ciderapp/Fujisan-BugTracker#82]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

When I sort the playlist by "added on" it doesn't work and if it does it is only available for a second.

https://user-images.githubusercontent.com/125579030/224511292-0513aec4-c464-4b27-98ee-17c53b6ce777.mp4

### Steps to Reproduce

1. Select "added on" for playlist sorting
2. reload the playlist

**Comment by coredev-uk** [comment]
Resolved in [ciderapp/proj](https://github.com/ciderapp/project2/pull/26)
