### ISSUE TITLE
[Bug]: Discord RPC

### ISSUE THREAD

**Issue by BENZORICH** [ciderapp/Fujisan-BugTracker#84]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11 22H2

### Describe the Bug

The Disocrd RPC is not displayed correctly I have set that there should be "Apple Music" but it says "Cider 2" and all settings are not taken correctly

![image](https://user-images.githubusercontent.com/125579030/224550522-b897009e-b064-413c-bc6d-56113966966f.png)
![image](https://user-images.githubusercontent.com/125579030/224550537-b1928073-3566-476d-8099-528d3b4ce281.png)

### Steps to Reproduce

1. Set RPC

**Comment by Monochromish** [comment]
Added support for it.
