### ISSUE TITLE
[Bug/Visual]: Current playing text container is left aligned in Mavericks layout

### ISSUE THREAD

**Issue by Enstrayed** [ciderapp/Fujisan-BugTracker#88]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1085025349643010130 2023-03-13

### Operating System Version

Windows 11 Pro 22H2 22624.1391

### Describe the Bug

The now playing bar has the text container aligned to the left instead of the center when using the mavericks layout.

![cider2nowplayingleftaligned](https://on.enstrayed.com/images/20230313cider2_nowplayingleftaligned.jpg)

this also affects the blur when hovering over the box to show the time remaining

![cider2nowplayingleftalignedhover](https://on.enstrayed.com/images/20230313cider2_nowplayingleftaligned_hover.jpg)

### Steps to Reproduce

1. play a song
2. observe the now playing box
3. optionally hover over the now playing box
4. observe it again

**Comment by TreehouseFalcon** [comment]
Also experiencing this.

**Comment by Swiftzerr** [comment]
Oopsie, I messed something up while trying to make the artist text click box smaller. Will fix this again

**Comment by Swiftzerr** [comment]
Fixed
