### ISSUE TITLE
[Bug]: Cider Audio Lab will not load at all

### ISSUE THREAD

**Issue by NotChanceBanana** [ciderapp/Fujisan-BugTracker#91]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1085025349643010130

### Operating System Version

Win 11 22H2

### Describe the Bug

![image](https://user-images.githubusercontent.com/123398780/224998665-08ffcbd4-843f-4ca3-a946-260fc045c0d8.png)
![image](https://user-images.githubusercontent.com/123398780/224998701-efe2bdcc-1a99-4836-9b6e-fb538a26a787.png)
Cider Audio Lab refuses to load on latest build.

### Steps to Reproduce

Open Cider, make sure Audio lab is enabled and visible, and attempt to open it to change settings.

**Comment by Swiftzerr** [comment]
Play a song first, then try using Audio Lab
