### ISSUE TITLE
[Bug]: Clicking Infinite Shuffle in Immersive Mode Pops Out of Immersive Mode.

### ISSUE THREAD

**Issue by TheDordo** [ciderapp/Fujisan-BugTracker#92]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

https://discord.com/channels/843954443845238864/905459703092490340/1085025349643010130

### Operating System Version

Windows 11 Pro 22H2

### Describe the Bug

Clicking Infinite Shuffle Button in Immersive Mode Takes You Out of Immersive Mode. It used to stay in immersive mode when doing so.

### Steps to Reproduce

1. Go into Immersive Mode
2. Click Infinite Shuffle

**Comment by Swiftzerr** [comment]
Fixed in latest commit
